# Generated by Django 5.2.6 on 2025-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='phone_numbers', to='dashboard.group'),
        ),
    ]
