# Generated by Django 5.2.6 on 2025-09-10 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rule_phonenumber_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='phone_numbers', to=settings.AUTH_USER_MODEL),
        ),
    ]
