# Generated by Django 5.2.6 on 2025-09-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_phonenumber_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='user',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_numbers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared_numbers', to=settings.AUTH_USER_MODEL),
        ),
    ]
