# Generated by Django 5.2.6 on 2026-02-23 08:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_group_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_port', models.CharField(default='/dev/ttyUSB0', max_length=100)),
                ('baud_rate', models.PositiveIntegerField(default=115200)),
                ('pin_code', models.CharField(blank=True, max_length=16)),
                ('apn', models.CharField(blank=True, max_length=100)),
                ('network_mode', models.CharField(choices=[('AUTO', 'Auto'), ('LTE_M', 'LTE-M'), ('NB_IOT', 'NB-IoT'), ('GSM', 'GSM')], default='AUTO', max_length=10)),
                ('sms_storage', models.CharField(choices=[('SIM', 'SIM'), ('MODEM', 'Modem'), ('BOTH', 'SIM + Modem')], default='SIM', max_length=10)),
                ('delivery_reports', models.BooleanField(default=True)),
                ('allow_incoming_sms', models.BooleanField(default=True)),
                ('auto_start_gateway', models.BooleanField(default=True)),
                ('heartbeat_interval_sec', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)])),
                ('webhook_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
