# Generated by Django 5.2.6 on 2026-02-23 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_gatewaysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('event_type', models.CharField(choices=[('SMS', 'Příchozí SMS'), ('CALL', 'Příchozí volání'), ('ANY', 'SMS i volání')], default='ANY', max_length=10)),
                ('match_type', models.CharField(choices=[('ANY', 'Jakékoliv číslo'), ('EXACT', 'Konkrétní číslo'), ('GROUP', 'Číslo ze skupiny')], default='ANY', max_length=10)),
                ('source_number', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('IGNORE', 'Ignorovat'), ('NOTIFY', 'Poslat informaci na cílová čísla'), ('FORWARD', 'Předat informaci na jedno číslo')], default='IGNORE', max_length=10)),
                ('forward_to_number', models.CharField(blank=True, max_length=30)),
                ('include_original_message', models.BooleanField(default=True)),
                ('custom_message', models.CharField(blank=True, max_length=320)),
                ('stop_processing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
                ('source_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_automation_rules', to='dashboard.group')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='targeted_by_rules', to='dashboard.group')),
                ('target_numbers', models.ManyToManyField(blank=True, related_name='targeted_by_rules', to='dashboard.phonenumber')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IncomingEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SMS', 'Příchozí SMS'), ('CALL', 'Příchozí volání')], max_length=10)),
                ('source_number', models.CharField(max_length=30)),
                ('message_body', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('result_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('NOTIFY_SMS', 'Notifikační SMS'), ('FORWARD_INFO', 'Předaná informace')], max_length=20)),
                ('target_number', models.CharField(max_length=30)),
                ('payload_message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Čeká'), ('SENT', 'Odesláno'), ('FAILED', 'Chyba')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dashboard.incomingeventlog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_actions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
