# Generated by Django 5.2.6 on 2026-02-23 09:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_automationrule_incomingeventlog_outgoingaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'Automatizační pravidlo', 'verbose_name_plural': 'Automatizační pravidla'},
        ),
        migrations.AlterModelOptions(
            name='gatewaysettings',
            options={'verbose_name': 'Nastavení brány', 'verbose_name_plural': 'Nastavení brány'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Skupina', 'verbose_name_plural': 'Skupiny'},
        ),
        migrations.AlterModelOptions(
            name='incomingeventlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Záznam příchozí události', 'verbose_name_plural': 'Záznamy příchozích událostí'},
        ),
        migrations.AlterModelOptions(
            name='outgoingaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Odchozí akce', 'verbose_name_plural': 'Odchozí akce'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Telefonní číslo', 'verbose_name_plural': 'Telefonní čísla'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Pravidlo', 'verbose_name_plural': 'Pravidla'},
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action',
            field=models.CharField(choices=[('IGNORE', 'Ignorovat'), ('NOTIFY', 'Poslat informaci na cílová čísla'), ('FORWARD', 'Předat informaci na jedno číslo')], default='IGNORE', max_length=10, verbose_name='Reakce'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='custom_message',
            field=models.CharField(blank=True, max_length=320, verbose_name='Vlastní text'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='event_type',
            field=models.CharField(choices=[('SMS', 'Příchozí SMS'), ('CALL', 'Příchozí volání'), ('ANY', 'SMS i volání')], default='ANY', max_length=10, verbose_name='Typ události'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='forward_to_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Předat na číslo'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='include_original_message',
            field=models.BooleanField(default=True, verbose_name='Přiložit původní zprávu'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='match_type',
            field=models.CharField(choices=[('ANY', 'Jakékoliv číslo'), ('EXACT', 'Konkrétní číslo'), ('GROUP', 'Číslo ze skupiny')], default='ANY', max_length=10, verbose_name='Typ podmínky'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Název pravidla'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='Priorita'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_automation_rules', to='dashboard.group', verbose_name='Zdrojová skupina'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='source_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Zdrojové číslo'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='stop_processing',
            field=models.BooleanField(default=True, verbose_name='Zastavit další vyhodnocení'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='targeted_by_rules', to='dashboard.group', verbose_name='Cílové skupiny'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='target_numbers',
            field=models.ManyToManyField(blank=True, related_name='targeted_by_rules', to='dashboard.phonenumber', verbose_name='Cílová čísla'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Upraveno'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='allow_incoming_sms',
            field=models.BooleanField(default=True, verbose_name='Povolit příchozí SMS'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='apn',
            field=models.CharField(blank=True, max_length=100, verbose_name='APN'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='auto_start_gateway',
            field=models.BooleanField(default=True, verbose_name='Automatické spuštění brány'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='baud_rate',
            field=models.PositiveIntegerField(default=115200, verbose_name='Přenosová rychlost (baud)'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='delivery_reports',
            field=models.BooleanField(default=True, verbose_name='Doručenky'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='heartbeat_interval_sec',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)], verbose_name='Interval heartbeat (s)'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='network_mode',
            field=models.CharField(choices=[('AUTO', 'Automaticky'), ('LTE_M', 'LTE-M'), ('NB_IOT', 'NB-IoT'), ('GSM', 'GSM')], default='AUTO', max_length=10, verbose_name='Síťový režim'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='pin_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='PIN SIM'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='serial_port',
            field=models.CharField(default='/dev/ttyUSB0', max_length=100, verbose_name='Sériový port'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='sms_storage',
            field=models.CharField(choices=[('SIM', 'SIM'), ('MODEM', 'Modem'), ('BOTH', 'SIM + Modem')], default='SIM', max_length=10, verbose_name='Úložiště SMS'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Naposledy změněno'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_settings', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='gatewaysettings',
            name='webhook_url',
            field=models.URLField(blank=True, verbose_name='Webhook URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelé'),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Čas přijetí'),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='event_type',
            field=models.CharField(choices=[('SMS', 'Příchozí SMS'), ('CALL', 'Příchozí volání')], max_length=10, verbose_name='Typ události'),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='message_body',
            field=models.TextField(blank=True, verbose_name='Obsah zprávy'),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_event_logs', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník'),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Zpracováno'),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='result_summary',
            field=models.TextField(blank=True, verbose_name='Výsledek zpracování'),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='source_number',
            field=models.CharField(max_length=30, verbose_name='Zdrojové číslo'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='action_type',
            field=models.CharField(choices=[('NOTIFY_SMS', 'Notifikační SMS'), ('FORWARD_INFO', 'Předání informace')], max_length=20, verbose_name='Typ akce'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='event_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dashboard.incomingeventlog', verbose_name='Zdrojová událost'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_actions', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='payload_message',
            field=models.TextField(verbose_name='Text akce'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.automationrule', verbose_name='Pravidlo'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Čeká'), ('SENT', 'Odesláno'), ('FAILED', 'Chyba')], default='PENDING', max_length=10, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='target_number',
            field=models.CharField(max_length=30, verbose_name='Cílové číslo'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='phone_numbers', to='dashboard.group', verbose_name='Skupiny'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Telefonní číslo'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelé se sdílením'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
    ]
