# Generated by Django 5.2.11 on 2026-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_automationrule_notification_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='match_type',
            field=models.CharField(choices=[('ANY', 'Jakékoliv číslo'), ('EXACT', 'Konkrétní číslo'), ('GROUP', 'Číslo ze skupiny'), ('OBJECT', 'Událost z objektu')], default='ANY', max_length=10, verbose_name='Typ podmínky'),
        ),
        migrations.AlterField(
            model_name='outgoingaction',
            name='action_type',
            field=models.CharField(choices=[('NOTIFY_SMS', 'Notifikační SMS'), ('NOTIFY_EMAIL', 'Notifikační e-mail'), ('NOTIFY_TEAMS', 'Notifikace do Teams'), ('FORWARD_INFO', 'Předání na číslo'), ('DEVICE_PULL', 'Vyzvednutí požadavku objektu')], max_length=20, verbose_name='Typ akce'),
        ),
    ]
