# Generated by Django 5.2.11 on 2026-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_automationrule_match_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='notification_emails',
            field=models.TextField(blank=True, verbose_name='Další e-maily pro notifikaci'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kontaktní e-mail'),
        ),
    ]
