# Generated by Django 5.2.11 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_automationrule_notification_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('SMS', 'Příchozí SMS'),
                    ('CALL', 'Příchozí volání'),
                    ('API', 'Příchozí API událost'),
                    ('SMS_CALL', 'SMS i volání'),
                    ('SMS_API', 'SMS i API událost'),
                    ('CALL_API', 'Volání i API událost'),
                    ('ANY', 'SMS i volání'),
                    ('ALL', 'SMS, volání i API událost'),
                ],
                default='ANY',
                max_length=20,
                verbose_name='Typ události',
            ),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('SMS', 'Příchozí SMS'),
                    ('CALL', 'Příchozí volání'),
                    ('API', 'Příchozí API událost'),
                ],
                max_length=20,
                verbose_name='Typ události',
            ),
        ),
    ]
