# Generated by Django 5.2.11 on 2026-02-27

from django.db import migrations, models


def migrate_object_match_type_to_any(apps, schema_editor):
    AutomationRule = apps.get_model('dashboard', 'AutomationRule')
    AutomationRule.objects.filter(match_type='OBJECT').update(match_type='ANY')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_expand_event_types_for_api_rules'),
    ]

    operations = [
        migrations.RunPython(migrate_object_match_type_to_any, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='automationrule',
            name='match_type',
            field=models.CharField(
                choices=[
                    ('ANY', 'Jakékoliv číslo'),
                    ('EXACT', 'Konkrétní číslo'),
                    ('GROUP', 'Číslo ze skupiny'),
                ],
                default='ANY',
                max_length=10,
                verbose_name='Typ podmínky',
            ),
        ),
    ]
