# Generated by Django 5.2.11 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_object_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingaction',
            name='execution_detail',
            field=models.TextField(blank=True, verbose_name='Detail zpracování'),
        ),
        migrations.AddField(
            model_name='outgoingaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zpracováno'),
        ),
    ]
