# Generated by Django 5.2.16 on 2026-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_gatewaysettings_signal_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='event_type',
            field=models.CharField(choices=[('SMS', 'Příchozí SMS'), ('API', 'Příchozí API událost'), ('SMS_API', 'SMS i API událost'), ('ANY', 'SMS i API událost')], default='ANY', max_length=20, verbose_name='Typ události'),
        ),
        migrations.AlterField(
            model_name='incomingeventlog',
            name='event_type',
            field=models.CharField(choices=[('SMS', 'Příchozí SMS'), ('API', 'Příchozí API událost')], max_length=20, verbose_name='Typ události'),
        ),
    ]
