"""
Django settings for gsm_gate project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Musí jít přes DJANGO_SECRET_KEY env proměnnou (.env, viz .env.example) -
# fallback níže je jen pro pohodlný lokální vývoj bez .env a je záměrně
# rozpoznatelný jako nebezpečný (Django ho i sám hlásí přes manage.py check
# --deploy, protože začíná "django-insecure-").
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-CHANGE-ME-please-set-DJANGO_SECRET_KEY-env-var',
)

# Verze appky a autor - zobrazuje se v patičce (base.html) přes context
# processor dashboard.context_processors.app_info. APP_AUTHOR je zatím
# prázdné - doplnit až bude jméno/přezdívka, kterou chceš zobrazovat.
APP_VERSION = '1.0.0'
APP_AUTHOR = ''

# Adresa běžícího MkDocs webu (docker-compose.mkdocs.yml) - používá se na
# odkazy "Dokumentace" v patičce/menu a u doporučení v Sebediagnostice.
# Bez koncového lomítka.
MKDOCS_BASE_URL = os.environ.get('MKDOCS_BASE_URL', 'http://10.10.10.234:8010').rstrip('/')

# SECURITY WARNING: don't run with debug turned on in production!
# Bezpečný default je vypnuto - zapíná se explicitně přes DJANGO_DEBUG=True v .env.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').strip().lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000,http://127.0.0.1:8000'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gsm_gate',
    'accounts',
    'django_extensions',
    'widget_tweaks',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gsm_gate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.app_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'gsm_gate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'user'),
        'USER': os.environ.get('DATABASE_USER', 'user'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'user'),
        'HOST': os.environ.get('DATABASE_HOST', 'db'),
        'PORT': os.environ.get('DATABASE_PORT', 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'cs-cz'
TIME_ZONE = 'Europe/Prague'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = '/usr/src/app/staticfiles/'

# WhiteNoise servíruje static soubory přímo z gunicorn procesu (komprimované,
# s hash ve jméně pro cache busting) - žádný samostatný nginx kontejner není
# potřeba. Vyžaduje `manage.py collectstatic` před startem (viz command v
# docker-compose.yml - běží při každém startu kontejneru, ne jen při buildu,
# protože STATIC_ROOT je uvnitř bind-mountované ./django_app).
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Django defaultně taguje messages.error() jako "error", ale Bootstrap zná
# jen "alert-danger" (žádný "alert-error"). base.html dělá `alert-{{ tags }}`,
# takže bez tohohle by chyby vypadaly jako neodbarvený alert.
MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


def _env_bool(name, default='false'):
    return os.environ.get(name, default).strip().lower() in {'1', 'true', 'yes', 'on'}


GSM_ENABLED = _env_bool('GSM_ENABLED', 'false')
GSM_MODEM_PORT = os.environ.get('GSM_MODEM_PORT', '/dev/ttyUSB0')
GSM_MODEM_BAUD = int(os.environ.get('GSM_MODEM_BAUD', '115200'))
GSM_MODEM_TIMEOUT = float(os.environ.get('GSM_MODEM_TIMEOUT', '3'))
GSM_WORKER_INTERVAL = int(os.environ.get('GSM_WORKER_INTERVAL', '10'))
GSM_MAX_ACTIONS_PER_CYCLE = int(os.environ.get('GSM_MAX_ACTIONS_PER_CYCLE', '30'))

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', 'false')
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', 'false')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@gsm-gate.local')
NOTIFY_EMAIL_SUBJECT_PREFIX = os.environ.get('NOTIFY_EMAIL_SUBJECT_PREFIX', '[GSM Gate]')
NOTIFY_TEAMS_TIMEOUT = float(os.environ.get('NOTIFY_TEAMS_TIMEOUT', '8'))
